# Generated by Django 3.2.18 on 2023-04-26 21:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateField()),
                ('step', models.DurationField()),
                ('atmosphereSingleLayer', models.FloatField()),
                ('valid_time', models.DateField()),
                ('pwat', models.FloatField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
