# Generated by Django 3.2.18 on 2023-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateField()),
                ('step', models.DurationField()),
                ('atmosphereSingleLayer', models.FloatField()),
                ('valid_time', models.DateField()),
                ('pwat', models.FloatField()),
            ],
        ),
    ]
