# Generated by Django 3.2.18 on 2023-06-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactiveMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='valid_time',
            field=models.DateTimeField(),
        ),
    ]
