# Generated by Django 3.2.18 on 2023-04-22 14:44

from django.db import migrations
import json


class Migration(migrations.Migration):

    dependencies = [
        ('interactiveMap', '0001_initial'),
    ]

    operations = [
    ]
