# Generated by Django 3.2.18 on 2023-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactiveMap', '0003_countryregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevantCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('all_regions', models.BooleanField()),
            ],
        ),
    ]
